### ISSUE TITLE
Uncaught ReferenceError: CIjs is not defined

### ISSUE THREAD

**Issue by cijagani** [JCSama/CodeIgniter-develbar#10]
Uncaught ReferenceError: CIjs is not defined

there is some mistake in ajax.js file. **it should be  CIjs not Ijs.**
![capture](https://cloud.githubusercontent.com/assets/3807730/24736294/c6aeda80-1aa4-11e7-99e1-2fcf528ed307.PNG)

**Comment by JCSama** [comment]
Thank you @truelineinfotech
