### ISSUE TITLE
Please guidance for mvc

### ISSUE THREAD

**Issue by vikaskumarmca** [JCSama/CodeIgniter-develbar#16]

**Comment by JCSama** [comment]
May I ask for more details !

**Comment by vikaskumarmca** [comment]
i want to config codeigniter 2 and 3 for mvc archecture

**Comment by dowadidi** [comment]
Hi @vikaskumarmca,

This is not the main CodeIgniter repository.
Here are some links you might find useful:
- The CodeIgniter repo: https://github.com/bcit-ci/CodeIgniter
- The CodeIgniter documentation: https://codeigniter.com/docs
- The CodeIgniter forum: https://forum.codeigniter.com

There's also a codeigniter tag on StackOverflow: https://stackoverflow.com/questions/tagged/codeigniter

Good luck!
