### ISSUE TITLE
Ajax requests can't work if not default templator used

### ISSUE THREAD

**Issue by Den4X** [JCSama/CodeIgniter-develbar#17]
$output = $this->CI->output->get_output(); //null;
$output = preg_replace('|<head>(.*?)<\/head>|is', '<head>'.$js.'$1</head>', $output, 1, $count); //so not work

very force hack, but work fine )
$develBarOutput = $this->develbar_output();
            // Patch for Pace.js or similar
            if (true == $this->default_options['develbar_sections']['Ajax']) {
                $js = $this->CI->load->file($this->assets_folder.'js/ajax.js', true);
                $js = '<script type="text/javascript">var cidvl_siteurl="'. site_url().'";'.$js.'</script>';
				$develBarOutput .= $js;
            }
            $this->CI->output->_display($develBarOutput);
            return;

**Comment by JCSama** [comment]
Hello @Den4X,
What do you mean by default templator ?
