### ISSUE TITLE
Breaking view when adding config data

### ISSUE THREAD

**Issue by Cedric-ruiu** [JCSama/CodeIgniter-develbar#2]
In my config files, if i add `$config['foobar'] = '<li>';` the develbar view is breaking. `<li>` seems to be the problem. (the green squares are from me)
![develbar-bugview](https://cloud.githubusercontent.com/assets/3066242/7468882/d3f025c0-f30d-11e4-9544-c28e676a31f5.png)

**Comment by JCSama** [comment]
Hi Cedric, 
thank you for reporting this issue, and sorry for the delay.
