### ISSUE TITLE
Cannot use object of type Closure as array

### ISSUE THREAD

**Issue by Iyongbudiarso** [JCSama/CodeIgniter-develbar#20]
I use another hook like `pre_system` and `post_controller_constructor`. And an error appears "Cannot use object of type closure as array. I have 2 problem in this

1. Cannot view hook if value of params is array (Array to string conversation)
2. Cannot use object of type Closure as array

Check my config hooks.php

![screenshot-localhost-8201-2017-10-11-09-32-45-550](https://user-images.githubusercontent.com/4843505/31418195-2d1c58f0-ae67-11e7-9a99-6d7ba658ed48.png)

My Request Pull #19

Thanks

**Comment by JCSama** [comment]
Hello @Iyongbudiarso 

Thanks for your contribution
