### ISSUE TITLE
How to implement with Blade - https://github.com/cntaoyu/CI-Blade

### ISSUE THREAD

**Issue by Iyongbudiarso** [JCSama/CodeIgniter-develbar#21]
Im using package "xiaoler/blade": "^5.4" for templating my project CI version 3.1.6
If I use library on CI `$this->load->view` debugbar is running normal
But If I use my Library Blade (https://pastebin.com/d9SNT5Xh), `$this->blade->view()` debugbar is not running

Thanks

**Comment by JCSama** [comment]
Hello @Iyongbudiarso 

> But If I use my Library Blade (https://pastebin.com/d9SNT5Xh), $this->blade->view() debugbar is not running

You mean the hole debugbar is not showing up, or just the view Tab ?

**Comment by Iyongbudiarso** [comment]
Hello @JCSama

No output anything, page just blank

**Comment by JCSama** [comment]
Any PHP errors ?

**Comment by Iyongbudiarso** [comment]
No @JCSama 
I think because Library https://github.com/cntaoyu/CI-Blade not using or passing `$this->load->view()`

Thanks before

**Comment by Iyongbudiarso** [comment]
Hello @JCSama 
This issue is closed, sorry that's my fault. 
I wrote function exit at the end

Thanks

**Comment by JCSama** [comment]
But still, the view tab is not gonna display anything, and you will need to change the character tag for blade to something different from {{,}}
