### ISSUE TITLE
AJAX panel not visible

### ISSUE THREAD

**Issue by shaheer912** [JCSama/CodeIgniter-develbar#22]
Hi,

I installed it on CodeIgniter 3.1.2, I see the develbar at the bottom, but I cant find a way to open the full AJAX panel.

Also there is a CSS issue with Database section, if too many queries are listed, it overlaps with the develbar, instead of appearing in a scrollbar.

**Comment by JCSama** [comment]
Hello @shaheer912 
Can you add a screenshot to your post ?

Thanks.

**Comment by shaheer912** [comment]
![screenshot1](https://user-images.githubusercontent.com/4784816/32421317-f952c8c2-c2b8-11e7-927d-154b1f8807a5.png)

Snapshot for css issue with database section is attached, I just noticed that it DOES show a scrollbar at some point (but not always).

I dont know how to show a screen shot for AJAX panel, it is not visible and I dont know how to open it.

Just to be clear, when I say AJAX panel, I mean this:
https://raw.githubusercontent.com/JCSama/CodeIgniter-develbar/gh-pages/images/Screen-Shot-develbar-profiler.png

You attached this on your repo page.

**Comment by JCSama** [comment]
Hello,
When you submit an Ajax request you will have a little panel that shows at
the bottom with a profiler link, you will have to copy the profiler
controller into your controllers folder.

I'll check this css bug.

Thanks

**Comment by shaheer912** [comment]
That is not what I meant when I said AJAX panel.
I specifically mentioned that in my above post.

I am quoting it again here:

> Just to be clear, when I say AJAX panel, I mean this:
https://raw.githubusercontent.com/JCSama/CodeIgniter-develbar/gh-pages/images/Screen-Shot-develbar-profiler.png
> 
> You attached this on your repo page.

**Comment by JCSama** [comment]
And I said :
> you will have to copy the profiler controller into your controllers folder.

and check your console if there is any JS errors.

**Comment by shaheer912** [comment]
I obviously did that, that's the only way the develbar in the bottom will show up in the first place and it is visible as shown in the screenshot I attached in my original post.

However following AJAX panel is not visible.
![screen-shot-develbar-profiler](https://user-images.githubusercontent.com/4784816/32812101-16aeaf18-c9c5-11e7-8952-bdf01c1c7572.png)

I checked my console, no JS errors.

**Comment by JCSama** [comment]
Do you use any library for you ajax requests, or it's just a native ones

**Comment by shaheer912** [comment]
I use jQuery, nothing else.
