### ISSUE TITLE
CI profiler not visible debug profiler view

### ISSUE THREAD

**Issue by prepared91** [JCSama/CodeIgniter-develbar#23]
Hi,

How to enable profiler view? (https://raw.githubusercontent.com/JCSama/CodeIgniter-develbar/gh-pages/images/Screen-Shot-develbar-profiler.png)

If develbar is enabled not showing profiler.
Welcome controller:

`<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Welcome extends CI_Controller {
	public function index()
	{
		$this->output->enable_profiler(TRUE);
	
		$this->load->view('welcome_message');
	}
}
![fireshot capture 5 - welcome to codeigniter - http___localhost_public_welcome](https://user-images.githubusercontent.com/11649918/34772924-1bb1815e-f60a-11e7-9342-3f6c4f3c5e89.png)

Disabled develbar
![fireshot capture 4 - welcome to codeigniter - http___localhost_public_welcome](https://user-images.githubusercontent.com/11649918/34772935-267b1dac-f60a-11e7-88cf-40d52cc69079.png)

Thanks for help.
Prepared

`

**Comment by JCSama** [comment]
Hello,

> How to enable profiler view?

It's enabled by default, by you need to copy the controllers/develbarprofiler.php to your controllers folder to see the details for your AJAX queries.

**Comment by prepared91** [comment]
I know and copied this file. Ajax is working:
![image](https://user-images.githubusercontent.com/11649918/34782740-e90c941c-f629-11e7-83ac-b442e26587a2.png)

![image](https://user-images.githubusercontent.com/11649918/34782373-c2655a84-f628-11e7-8ba1-0b404a64b76c.png)

Where do I find this view or how can I open it (full page view)? (https://raw.githubusercontent.com/JCSama/CodeIgniter-develbar/gh-pages/images/Screen-Shot-develbar-profiler.png)

**Comment by JCSama** [comment]
Good, you're almost there, now within your ajax panel on the right, you'll see a link that open up the page you're looking for.

**Comment by prepared91** [comment]
Should it be here?
![image](https://user-images.githubusercontent.com/11649918/34783768-b4082e72-f62c-11e7-9c35-929f6d373c4d.png)

**Comment by JCSama** [comment]
Yes, but it's not there...what about you cache folder, does it have a (read/write) permissions !

**Comment by prepared91** [comment]
![image](https://user-images.githubusercontent.com/11649918/34787903-30da3b00-f639-11e7-873f-b0965f8d7e4d.png)

Yes, there is writing and reading permission for the cache directory. (testing: localhost, permissions: administrator user + all user + system etc)

**Comment by JCSama** [comment]
What about your Ajax query, was it completed ?

**Comment by prepared91** [comment]
The return data is just "echo hello world".
```
class Ajax_grid extends CI_Controller {
  
  function users(){
		echo 'Hello World';
  }
}
```
if I open ajax url it seams:
![fireshot capture 9 - - http___localhost_regirend_ujci_ajax php__admin_ajax_grid_users](https://user-images.githubusercontent.com/11649918/34794460-02973d2c-f64f-11e7-9825-5f32227e2caa.png)

**Comment by JCSama** [comment]
Any JS errors ?

**Comment by prepared91** [comment]
there is 
`Uncaught ReferenceError: cidvl_siteurl is not defined
    at i ((index):147)
    at XMLHttpRequest.<anonymous> ((index):147)`

**Comment by yahyaerturan** [comment]
I came up with the same error: `cidvl_siteurl is not defined`

As a solution I added the following to `ajax.js`:

```javascript
var cidvl_siteurl = "http://clinic-management.local/";
``` 

Then profile link in ajax tab starts to be shown. But when I click it says `Profiler key has expired :(`

**Comment by JCSama** [comment]
I see, just refresh the Page. I'll fix this error later.

**Comment by yahyaerturan** [comment]
Just for reference:

I did even change `ttl` in cached file, and checked profiler link's uuid with cahced file's name (which is same, I guess it should be like this).

Rest is up to you. Hope those help to contribute a bit.

```json
a:3:{s:4:"time";i:1515627205;s:3:"ttl";i:1800;s:4:"data";a:6:{s:13:"ajax_requests";a:5:{s:4:"icon";s:1918:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDpEOUY4RDdGMUQwREExMUU0OUU1NkQyMTA5QzM2RUM0NSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDpEOUY4RDdGMkQwREExMUU0OUU1NkQyMTA5QzM2RUM0NSI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOjcyMEQzODEwRDBDMjExRTQ5RTU2RDIxMDlDMzZFQzQ1IiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOkQ5RjhEN0YwRDBEQTExRTQ5RTU2RDIxMDlDMzZFQzQ1Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+5+QVXgAAAgBJREFUeNqc1FtIFFEcx/FZd8MkMoKoEIosi6B7WekWIWhoiUX2VFSQEu1Dz1EgGKg9h5eNQIN6NBO8gEWCSbSF2c16SIVIIU3YzKQreOn7h18wII07Hfiws2dmfnM4539OYCLb+Z/WiCyUI47BJbHZd3Yj4DNwPS7jBD5iAmuxFBsJ7U/yEXYcA/otRQZycRXTiNhDIR+BK/ETF/EClfiMZizCla/hwG8/I7SPv8cNnHZNgY3yJqaw2U/gNWxCMnqwAkG8wTa8QpmfwHNahOt4i060YBIXkInUfwXutlJAP7aor16jPIsqTYG9X4F9uGtz6y6bHK2cTf4x7FT/M9XdqEYYUZmk6JlPKKJket11WIRWBYwhhteYwQHsxWL1HcYIwjiKKGFD7pWztl2/j9GGe3rZ2h6FHMEOK2AF2kdjhM0pBUer9gMPUK16S9IIezSf6Qob91o5e+kkbmMYHQorxiM0YRm+oFbbzaYmzyvwFJZrFN/Ub6XRoNW+pD7bdk+wCvlegTaqX3owRf1VKo8PuKW+NGzFdzz12k41OoJsS+3Hc83jQ43673xauWxQSd33CnRUEgtRqBG0o0/31uEQdmGB7jvzBYb08EGs0Z59qXu2CwqwWv+DiQRGrch1WCarYEt0zsV1RNl1F7oTCbRW57o+o71r7TzuJHqC/BFgAE3IgNgLytIFAAAAAElFTkSuQmCC";s:6:"method";s:4:"post";s:10:"controller";s:15:"CacheController";s:6:"action";s:19:"xhrClearCacheFolder";s:10:"parameters";a:0:{}}s:8:"database";a:2:{s:4:"icon";s:1858:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAAAUCAYAAABroNZJAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDpEOUY4RDdGOUQwREExMUU0OUU1NkQyMTA5QzM2RUM0NSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDpEOUY4RDdGQUQwREExMUU0OUU1NkQyMTA5QzM2RUM0NSI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOkQ5RjhEN0Y3RDBEQTExRTQ5RTU2RDIxMDlDMzZFQzQ1IiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOkQ5RjhEN0Y4RDBEQTExRTQ5RTU2RDIxMDlDMzZFQzQ1Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+XPsfIAAAAdFJREFUeNqclMsrRGEYxs/cXXKZcWlcilFTUjZyLTY2ykKIsLClbK3s5F+wkyyULFgRCxtZGLlt2FEKaYgYZCaMGc/Do06TmZi3fs2Zc77znvd9nvf7LKEWg2EDPtAAukETqDC+Iwasug6CPbACtsFFXiAesSCJF38mwagWnoEHENJLYeACJSAfeEAlsINlMMGLBdAOXsAwWAVRI3lYQCtYAn3AzzKb9fADlIECffm3cKqacvCuez62c4OLYtPCU7XyrLZYYSZwgxxRY1p/Y5eo5vAb/wsH25kDr0Z6Qec2rHKmE+yCE7mRKt7k4D4YohlsZx7MmATmjNRJZI9EpoiP4Aocg02trQfTFDauG7R6CxyBS4kaSXDGreS1oBGMfXmOJBwob0LJt3InrJmxySE6U5hgRtCu4UmMIvGXcFLYEfCUpjtsd4qVBLT5esA4yFLp/HWo9JjEjZjgaMzyOZMcUmGwLrXD2rXVoFTJOEfXGoGIkleBLn6Ywt5KLENbfI2jDO7UZlQ7NlvruLc6QK/sv2cS+p+bYrDelSTZprxn2eeplFcFrlTiMskg2EnTHWo0YNHx+HNa9YM2nRl0KMPkzqtEp04HYJF7CMfj9acAAwDhEnOxHmuHkwAAAABJRU5ErkJggg==";s:3:"dbs";a:1:{s:19:"CacheController:$db";O:19:"CI_DB_mysqli_driver":76:{s:8:"dbdriver";s:6:"mysqli";s:8:"compress";b:0;s:11:"delete_hack";b:1;s:8:"stricton";b:0;s:15:"
```

**Comment by JCSama** [comment]
Thank you guys.
