### ISSUE TITLE
How to find profiler ID?

### ISSUE THREAD

**Issue by gerardbalaoro** [JCSama/CodeIgniter-develbar#24]
After installing (copying files), I don't know how to proceed. When I go to develbarprofiler/profil it asks for a profileID, which is not mentioned in the documentation.

I also noticed it does not create files inside the cache folder.

**Comment by JCSama** [comment]
Hello @GerardBalaoro 
Do you have any Ajax queries within your page ? If you do so, the ajax panel will show up with a small profil link, when you click on it, it will redirect you to the profiler page.
