### ISSUE TITLE
ajax.js problem on profilerLink

### ISSUE THREAD

**Issue by foxmedo** [JCSama/CodeIgniter-develbar#28]
i have detect a problem on profilerLink 

i'm getting this error Uncaught (in promise) ReferenceError: profilerLink is not defined

can share with us ajax.js the original file cause this one is minified and variables has been changed 

i have solve the problem but add comment to 

`/*""!=b.profiler&&(profilerLink.textContent="profiler",n.appendChild(n)),*/`

waiting for your feedback 

B.R

**Comment by JCSama** [comment]
@foxmedo Thank you for reporting this, I'll take a look at it.

**Comment by cijagani** [comment]
[ajax.zip](https://github.com/JCSama/CodeIgniter-develbar/files/2706099/ajax.zip)
@foxmedo  may be you want above file.
