### ISSUE TITLE
Autoloading Database in the config.php

### ISSUE THREAD

**Issue by rmfitcocoy** [JCSama/CodeIgniter-develbar#29]
- Expected behavior and actual behavior.
hello when adding autoloading the database in the config.php, we should expect to see the database setup
but what happen either no data will return when hover on the database icon or and error  will return, here is the attach screenhot
![image](https://user-images.githubusercontent.com/40483056/47977408-cd8bd180-e0f2-11e8-99b4-000f5d83b50f.png)

- Steps to reproduce the problem.
I just simply autoload the libraty database in the config.php

- Specifications like the version of the project, operating system, or hardware.
I use the latest CI 3.1.9 with mysql in windows 10 running in IIS

also for my basic work around, i simply change the object to array return function in views database.php, here is the below
![image](https://user-images.githubusercontent.com/40483056/47977485-3b37fd80-e0f3-11e8-83ea-737ce04fefcf.png)

**Comment by JCSama** [comment]
Thanks @rmfitcocoy, I'll look into it.
