### ISSUE TITLE
missing data handle vars parsed to views and/or complete trace files

### ISSUE THREAD

**Issue by mckaygerhard** [JCSama/CodeIgniter-develbar#8]
i cannot see the data boject with all the vars parsed to views?!

```
		$data['objetousuario1'] = $object1->result();
		$data['objetousuario2'] = $object2->result();
		$this->load->view('header.php',$data);
		$this->load->view('adm_indicadores_verdata.php',$data);
		$this->load->view('footer.php',$data);
```

develbar does not offers to user two important things:

1) complete trace of files loaded secuence (see forensics addon) with each time spend
2) complete vars manage into views also inte session

also db objects are overriting by default object see comments in #7 if i have a default db instance, each other are not handle!

**Comment by JCSama** [comment]
Did you follow the installation instructions ? I think you did not add the core/MY_loader file.
The loaded view files are managed also the session variables, but not the view variables, coz you can go to your view file and dump the vriable.

**Comment by mckaygerhard** [comment]
i think u dont understand, the profiler does not show the view variables, all the rest works as expected and very good, nice gui of the profiler. the forensics profiler can able to do that and also some features more!

wil be nice if u'r profiler can do that...if u want ... by now i use the forensics codeigniter profiler.

**Comment by JCSama** [comment]
note taken for the next release, thank you @mckaygerhard

**Comment by JCSama** [comment]
done, you can check the release 0.7 updated

**Comment by mckaygerhard** [comment]
great, but a NOTE: representation of vars and each loaded file including the core loaded  and trace are

as i said currently only shows loaded views files, and not which file gets the framework pass and run..

and a question: why only support CI 2.2.X and not 2.1.X ?

**i dont know why a tool that its for develop are so eye-candy...**
