### ISSUE TITLE
Call to undefined function lang() 

### ISSUE THREAD

**Issue by dlzi** [JCSama/CodeIgniter-develbar#9]
I'm getting this error when I try to run it:

ERROR - 2017-03-31 10:57:17 --> Severity: error --> Exception: Call to undefined function lang() /Users/acme/Public/Websites/demo.dev/application/third_party/DevelBar/views/develbar/benchmarks.php 1

**Comment by JCSama** [comment]
Hello @danielzilli 
It seems like the language helper is not loaded, did you changed anything within the library ?
I can't reproduce this bug.

**Comment by dlzi** [comment]
Never mind. The problem is within my CMS. 
Thank you.
